export const TOGGLE_HINTS = 'TOGGLE_HINTS'
export const UPDATE_BOARD = 'UPDATE_BOARD'
export const ANALYZE_BOARD = 'ANALYZE_BOARD'
export const CLEAR_HINTS = 'CLEAR_HINTS'
export const SET_LEVEL = 'SET_LEVEL'
export const SET_BOARD = 'SET_BOARD'
export const RESET_GAME = 'RESET_GAME'
